---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/applications":
    get:
      summary: Retrieves all applications
      tags:
      - Applications
      responses:
        '200':
          description: applications found
    post:
      summary: Creates a new application
      tags:
      - Applications
      parameters: []
      responses:
        '201':
          description: application created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/applications/{token}":
    get:
      summary: Retrieves a specific application
      tags:
      - Applications
      parameters:
      - name: token
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: application found
        '404':
          description: application not found
    patch:
      summary: Updates an application name
      tags:
      - Applications
      parameters:
      - name: token
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: application updated
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/applications/{application_token}/chats":
    get:
      summary: Retrieves all chats for an application
      tags:
      - Chats
      parameters:
      - name: application_token
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: chats found
    post:
      summary: Creates a new chat for an application
      tags:
      - Chats
      parameters:
      - name: application_token
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: chat created
  "/applications/{application_token}/chats/{chat_number}":
    get:
      summary: Retrieves a specific chat
      tags:
      - Chats
      parameters:
      - name: application_token
        in: path
        required: true
        schema:
          type: string
      - name: chat_number
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: chat found
        '404':
          description: chat not found
  "/applications/{application_token}/chats/{chat_number}/messages":
    get:
      summary: Retrieves all messages for a chat
      tags:
      - Messages
      parameters:
      - name: application_token
        in: path
        required: true
        schema:
          type: string
      - name: chat_number
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: messages found
    post:
      summary: Creates a new message for a chat
      tags:
      - Messages
      parameters:
      - name: application_token
        in: path
        required: true
        schema:
          type: string
      - name: chat_number
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: message created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
              required:
              - body
  "/applications/{application_token}/chats/{chat_number}/messages/search":
    get:
      summary: Searches messages in a chat
      tags:
      - Messages
      parameters:
      - name: application_token
        in: path
        required: true
        schema:
          type: string
      - name: chat_number
        in: path
        required: true
        schema:
          type: string
      - name: query
        in: query
        schema:
          type: string
      responses:
        '200':
          description: messages found
        '404':
          description: chat not found
servers:
- url: http://127.0.0.1:3000
  variables:
    defaultHost:
      default: http://127.0.0.1:3000
