default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] { root }%>
  password: <%= ENV['DATABASE_PASSWORD'] { password }%>
  host: <%= ENV['DATABASE_HOST'] { db }%>  # Updated to point to the Docker service name
  port: 3306

development:
  <<: *default
  database: chat_system

test:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] { chat_system }%>
  username: <%= ENV['DATABASE_USERNAME'] { root }%>
  password: <%= ENV['DATABASE_PASSWORD'] { password }%>
  host: <%= ENV['DATABASE_HOST'] { db }%>